#Application url
url_old = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url = http://localhost/orangehrm/orangehrm-5.8/web/index.php/auth/login

#credentials
username = orangehrm1
password = aDmin$1234

#browser
browser = chrome 

#ImplicitWaitTime
implicitWait = 5

#ExplicitWait
explicitWait = 30