seleniumGrid=true
gridURL=http://localhost:4444/

#Application url
url_base = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url_local = http://localhost/orangehrm/orangehrm-5.8/web/index.php/auth/login
url_grid = http://host.docker.internal/orangehrm/orangehrm-5.8/web/index.php/auth/login

#credentials
username = orangehrm1
password = aDmin$1234

#browser
browser = chrome 

#ImplicitWaitTime
implicitWait = 5

#ExplicitWait
explicitWait = 30